# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Project/Vivado/project/project.cache/wt [current_project]
set_property parent.project_path D:/Project/Vivado/project/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo d:/Project/Vivado/project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Project/Matlab/OV7670/test.coe
add_files -quiet d:/Project/Vivado/project/project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/Project/Vivado/project/project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet d:/Project/Vivado/project/project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files d:/Project/Vivado/project/project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Project/Vivado/project/project.srcs/sources_1/imports/V/I2C_Controller.v
  D:/Project/Vivado/project/project.srcs/sources_1/imports/file_vga/vga.v
  D:/Project/Vivado/project/project.srcs/sources_1/new/RAM_controller.v
  D:/Project/Vivado/project/project.srcs/sources_1/new/imageReader.v
  D:/Project/Vivado/project/project.srcs/sources_1/imports/V/I2C_CCD_Config.v
  D:/Project/Vivado/project/project.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/Vivado/project/project.srcs/constrs_1/new/OV7670.xdc
set_property used_in_implementation false [get_files D:/Project/Vivado/project/project.srcs/constrs_1/new/OV7670.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
